POST https://pass-in-nodejs.vercel.app/events
Content-Type: application/json

{
    "title": "NLW Unite",
    "details": "15ª edição do NLW da Rocketseat.",
    "maximumAttendees": 20
}

###
POST https://pass-in-nodejs.vercel.app/events/7f968e71-187e-469e-95b1-dc861048194d/attendees
Content-Type: application/json

{
    "name": "Dave Lombardo",
    "email": "davelombardo@gmail.com"
}

###
GET https://pass-in-nodejs.vercel.app/events/7f968e71-187e-469e-95b1-dc861048194d

###
GET https://pass-in-nodejs.vercel.app/attendees/1/badge

###
GET https://pass-in-nodejs.vercel.app/attendees/5/check-in

###
GET https://pass-in-nodejs.vercel.app/events/7f968e71-187e-469e-95b1-dc861048194d/attendees