POST http://localhost:3333/events
Content-Type: application/json

{
    "title": 1,
    "details": null,
    "maximumAttendees": 5
}

###
POST http://localhost:3333/events/7f968e71-187e-469e-95b1-dc861048194d/attendees
Content-Type: application/json

{
    "name": "Mike Portnoy",
    "email": "portnoy.mike2@gmail.com"
}

###
GET http://localhost:3333/events/7f968e71-187e-469e-95b1-dc861048194d

###
GET http://localhost:3333/attendees/1/badge

###
GET http://localhost:3333/attendees/1/check-in

###
GET http://localhost:3333/events/7f968e71-187e-469e-95b1-dc861048194d/attendees