### Cria um evento
POST https://pass-in-nodejs.vercel.app/events
Content-Type: application/json

{
    "title": "NLW Unite",
    "details": "15ª edição do NLW da Rocketseat.",
    "maximumAttendees": 20
}

### Retorna um evento (passar ID)
GET https://pass-in-nodejs.vercel.app/events/bb4f1c2b-33ea-4053-8818-ca4ab69114de

### Retorna todos os eventos
GET https://pass-in-nodejs.vercel.app/events

### Registra um participante no evento (passar ID)
POST https://pass-in-nodejs.vercel.app/events/7f968e71-187e-469e-95b1-dc861048194d/attendees
Content-Type: application/json

{
    "name": "Bruno Graveto",
    "email": "bruno-graveto@gmail.com"
}

### Retorna todos os participantes de um evento (passar ID)
GET https://pass-in-nodejs.vercel.app/events/bb4f1c2b-33ea-4053-8818-ca4ab69114de/attendees

### Realiza check-in do participante
GET https://pass-in-nodejs.vercel.app/attendees/1/check-in

### Retorna a credencial de um participante 
GET https://pass-in-nodejs.vercel.app/attendees/1/badge